Update a bit to make it sorta work, vivado sunth errors
[nickoe@x280-arch nmigen-boards]$ echo $VIVADO
/opt/Xilinx/Vivado/2020.2/bin/vivado
[nickoe@x280-arch nmigen-boards]$ python3 -m nmigen_boards.basys3

****** Vivado v2020.2 (64-bit)
  **** SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
  **** IP Build 3064653 on Wed Nov 18 14:17:31 MST 2020
    ** Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.

source top.tcl
\# create_project -force -name top -part xc7a35tcpg236-1
\# add_files top.v
\# read_xdc top.xdc
\# synth_design -top top
Command: synth_design -top top
Starting synth_design
Using part: xc7a35tcpg236-1
Attempting to get a license for feature 'Synthesis' and/or device 'xc7a35t'
INFO: [Common 17-349] Got license for feature 'Synthesis' and/or device 'xc7a35t'
INFO: [Device 21-403] Loading part xc7a35tcpg236-1
INFO: [Synth 8-7079] Multithreading enabled for synth_design using a maximum of 4 processes.
INFO: [Synth 8-7078] Launching helper process for spawning children vivado processes
INFO: [Synth 8-7075] Helper process launched with PID 562883
ERROR: [Synth 8-2715] syntax error near " [/home/nickoe/nmigen_test/nmigen-boards/build/top.v:53]
INFO: [Synth 8-2350] module top ignored due to previous errors [/home/nickoe/nmigen_test/nmigen-boards/build/top.v:37]
Failed to read verilog '/home/nickoe/nmigen_test/nmigen-boards/build/top.v'
INFO: [Common 17-83] Releasing license: Synthesis
7 Infos, 0 Warnings, 0 Critical Warnings and 2 Errors encountered.
synth_design failed
ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details
INFO: [Common 17-206] Exiting Vivado at Tue Jan 26 23:06:13 2021...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nickoe/nmigen_test/nmigen-boards/nmigen_boards/basys3.py", line 202, in <module>
    Basys3Platform().build(Blinky(), do_program=True)
  File "/home/nickoe/litex_test2/nmigen/nmigen/build/plat.py", line 99, in build
    products = plan.execute_local(build_dir)
  File "/home/nickoe/litex_test2/nmigen/nmigen/build/run.py", line 98, in execute_local
    subprocess.check_call(["sh", "{}.sh".format(self.script)])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', 'build_top.sh']' returned non-zero exit status 1.